### ISSUE TITLE
DateTimeField received a naive datetime (django integration)

### ISSUE THREAD

**Issue by egrubbs** [activefrequency/pyavatax#11]
Hi,

I'm getting:
```RuntimeWarning: DateTimeField received a naive datetime (2015-11-27 13:07:41.268110) while time zone support is active.```

This can be fixed by changing datetime.datetime.now() to django.utils.timezone.now().
https://docs.djangoproject.com/en/dev/ref/utils/#django.utils.timezone.now

```
  File "/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/pyavatax/django_integration.py", line 33, in success
    AvaTaxRecord.objects.filter(doc_code=getattr(doc, 'DocCode', None)).update(success_on=datetime.datetime.now())
  File "/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/django/db/models/query.py", line 581, in update
    rows = query.get_compiler(self.db).execute_sql(None)
  File "/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1020, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 836, in execute_sql
    sql, params = self.as_sql()
  File "/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 985, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 304, in get_db_prep_save
    prepared=False)
  File "/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 836, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 825, in get_prep_value
    import traceback; traceback.print_stack()
/home/egrubbs/.virtualenvs/project/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:828: RuntimeWarning: DateTimeField received a naive datetime (2015-11-27 13:07:41.268110) while time zone support is active.
  RuntimeWarning)
```

**Comment by jobelenus** [comment]
Interesting, I'm curious which version of Django you're running? I definitely want to solve this.

**Comment by jobelenus** [comment]
I've fixed the TZ problem as you suggested. It is in 1.3.6. Do let me know if you encounter any other issues.

**Comment by egrubbs** [comment]
Thanks! I encountered this problem running Django 1.5, but it looks like it still exists in Django 1.8 in DateTimeField.get_prep_value().

**Comment by kgrinberg** [comment]
Can you check if it's fixed in the latest release of PyAvaTax (1.3.6)?
